name: flutter_segment
description: Flutter implementation of Segment Analytics for iOS, Android and Web
version: 3.13.5
homepage: https://lahaus.com
repository: https://github.com/la-haus/flutter-library-segment
issue_tracker: https://github.com/la-haus/flutter-library-segment/issues
documentation: https://github.com/la-haus/flutter-library-segment#readme

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: 1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_segment
        pluginClass: FlutterSegmentPlugin
      ios:
        pluginClass: FlutterSegmentPlugin
      web:
        pluginClass: SegmentWeb
        fileName: segment_web.dart
